name: taptapchef
description: A clicker-style mobile game built with Flutter.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.6.1
  audioplayers: ^5.2.1
  riverpod_annotation: ^2.6.1


# The following adds the Cupertino Icons font to your application.
# Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1  # or the latest version
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "TapTapIcon.jpg"
