name: taptapchef
description: A clicker-style mobile game built with Flutter.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  audioplayers: ^5.2.1

# The following adds the Cupertino Icons font to your application.
# Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1  # or the latest version

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/cook.wav
    - assets/sounds/cash.wav
    - assets/sounds/ui.wav
