name: taptapchef
description: A clicker-style mobile game built with Flutter.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2w
  flutter_riverpod: ^2.4.0
  audioplayers: ^5.2.1


# The following adds the Cupertino Icons font to your application.
# Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1  # or the latest version

flutter:
  uses-material-design: true
